### ISSUE TITLE
Dev instance tries to post to the production environment

### ISSUE THREAD

**Issue by Ghostbird** [bcc-its/darts#2]
Throwing a dart in a local development environment will freeze the game and display this warning:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://aslaksen.bcc.no/wp-json/darts-game/throw?_wpnonce=bc9f9b4927. (Reason: CORS request did not succeed).

And this error:

>  TypeError: "NetworkError when attempting to fetch resource."

Therefore, debugging is rather hard.

**Comment by frankblom** [comment]
Urls have been changed to the dev enviorment.
